# Generated by Django 3.1.5 on 2021-01-25 19:28
from datetime import datetime
from django.db import migrations

def create_data(apps, schema_editor):
    Projects = apps.get_model('projects', 'Projects')
    Projects(
        name="Proyecto prueba",
        desc="Proyecto prueba",
        creation_date=datetime.now()
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
