# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - database.env
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 60s

  bpmnus:
    image: edgarceron1993/bpmnus
    restart: always
    volumes:
      - /var/www/static/
    ports:
      - 8020:8020
    entrypoint:
      - /bin/bash
      - -c
      - "wait-for-it db:5432 -s -t 60 -- python manage.py migrate"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: edgarceron1993/nginxbpmnus
    depends_on:
      - bpmnus
      - bpmnusfront
    restart: always
    ports:
      - "80:80"
