# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - database.env
    volumes:
      - /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bpmnus"]
      interval: 5s
    ports:
      - 5432:5432

  migration:
    image: edgarceron1993/bpmnus
    command: python manage.py migrate --noinput
    volumes:
      - /var/www/static/
    depends_on:
      db:
        condition: service_healthy

  bpmnus:
    image: edgarceron1993/bpmnus
    restart: always
    volumes:
      - /var/www/static/
    depends_on:
      - migration

  bpmnusfront:
    image: edgarceron1993/bpmnusfront

  nginx:
    image: edgarceron1993/nginxbpmnus
    depends_on:
      - bpmnus
      - bpmnusfront
    restart: always
    ports:
      - 80:80
