# Generated by Django 3.2.7 on 2022-01-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagrams',
            name='file',
        ),
    ]
