# Generated by Django 3.2.7 on 2022-01-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0002_remove_diagrams_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagrams',
            name='xml',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
